### ISSUE TITLE
Error When Disabling Module

### ISSUE THREAD

**Issue by jcolas15** [webscale-networks/magento-varnish-api#8]
When attempting to disable the module on Magento ver. 2.4.6-p4 and PHP 8.1:

`Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /srv/<site>/html/vendor/webscale-networks/magento-varnish-api/Helper/Config.php on line 156`

and 

`Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /srv/www.prosci.com/html/vendor  
  /webscale-networks/magento-varnish-api/Helper/Config.php on line 144`

The value in the db for `webscale_varnish/cache_events/flush_all_events` and `webscale_varnish/cache_events/partial_invalidate_events` is set to null, which is likely causing the error

**Comment by serzhik** [comment]
@jcolas15 it looks like it is fixed in the latest version

**Comment by jcolas15** [comment]
Hey @serzhik One issue i see with the latest version 1.2.2 which says compatibility with PHP 8.2 https://github.com/webscale-networks/magento-varnish-api/releases is the composer.json does not have the php 8.2 dependency in composer.json 

https://github.com/webscale-networks/magento-varnish-api/blob/main/composer.json

**Comment by igor-webscale** [comment]
@jcolas15 it does have a support for php 8.2 - "^8.1" is [an equivalent](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) to ">8.1.* < 9.0.0".
